### ISSUE TITLE
Suggestion: Add GitHub pages link to repo

### ISSUE THREAD

**Issue by wish13yt** [mpax235/Windows-7-Simulator-on-Web#2]
its ez, click this 
![image](https://github.com/user-attachments/assets/6fc9d16d-8c5c-4f5a-ae65-cd25103d7dc5)
then click this
![image](https://github.com/user-attachments/assets/9f302f44-7620-4732-a3e7-5243e11722d7)
and then save changes

**Comment by mpax235** [comment]
got it!
